### ISSUE TITLE
Error when there is no success callback

### ISSUE THREAD

**Issue by LuisGuadagnin** [christian-fei/Simple-Jekyll-Search#137] opened 2020-03-22 21:02 UTC
Since yesterday I've been getting an error on my project when the `success` property is undefined in the options of the `SimpleJekyllSearch` function.
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at w.SimpleJekyllSearch (simple-jekyll-search.min.js:6)
    at toArticleSearch (search.js:204)
    at HTMLAnchorElement.<anonymous> (search.js:229)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)
    at Object.trigger (jquery.min.js:2)
    at HTMLAnchorElement.<anonymous> (jquery.min.js:2)
    at Function.each (jquery.min.js:2)
    at e.fn.init.each (jquery.min.js:2)
    at e.fn.init.trigger (jquery.min.js:2)
```

By debugging the non minified library, I found that the success callback is always called, even if it doesn't exist.
```
  window.SimpleJekyllSearch = function (_options) {
    var search = simpleJekyllSearch(_options)
    _options.success.call(search)
    return search
  }
```
In the documentation, it still says `success` is not a required option, so I guess this must be a bug.

**Comment by ChangUk** [comment] 2020-04-15 06:26
`options` merges with `_options` and then the merged is stored at `options`.
So, the statement `_options.success.call(search)` should be replaced with `options.success.call(search)`.
In minified version, `return t.success.call(e),e}}();` should be replaced with `return y.success.call(e),e}}();`.

**Comment by christian-fei** [comment] 2020-05-07 09:45
Hello,

thanks for your interest, will look into it when I find some time!

**Comment by christian-fei** [comment] 2020-06-23 06:55
@LuisGuadagnin is there a website where i can reproduce this?

perhaps try to update to the latest version 1.7.8

**Comment by HorlogeSkynet** [comment] 2020-07-15 18:07
Can still reproduce against v1.7.9, should be re-opened IMHO.

**Comment by christian-fei** [comment] 2020-07-15 18:59
do you have an example url @HorlogeSkynet ? 

happy to reopen if i can reproduce the issue, or someone has a PR

**Comment by HorlogeSkynet** [comment] 2020-07-15 19:07
No 'cause I didn't update SJS in production due to this error, occurring since v1.7.3 .
I think you should be able to reproduce yourself by using my configuration (no `success` callback as the OP noted) :

```javascript
var sjs = SimpleJekyllSearch({
	searchInput: document.getElementById('search-input'),
	resultsContainer: document.getElementById('results-container'),
	searchResultTemplate: '<li><a href="{url}" title="{title}" target="_blank">{title}</a></li>',
	json: '/search.json',
	noResultsText: '',
	fuzzy: true
});
```

**Comment by christian-fei** [comment] 2020-07-16 07:39
If you are able to, please make a PR @HorlogeSkynet

**Comment by HorlogeSkynet** [comment] 2020-07-16 07:41
Sorry I don't, if I were I would have already done it.

**Comment by ecupaio** [comment] 2020-07-16 13:57
to translate for @HorlogeSkynet, we have implemented the code exactly how it says to in the documentation and it does not work. We have no idea what changes broke the implementation the way we had it. version 1.7.3 is the latest version we are able to run without the plugin breaking and throwing the error `success is not a required option`. We are opening an issue because we do not know how to fix your plugin.

**Comment by christian-fei** [comment] 2020-07-16 14:35
please try with the updated package

https://unpkg.com/simple-jekyll-search@1.7.11/dest/simple-jekyll-search.min.js

**Comment by ecupaio** [comment] 2020-07-16 14:48
That seems to do the trick on my end. Thanks @christian-fei. Is this version 1.7.11?

**Comment by christian-fei** [comment] 2020-07-16 15:02
Yep!

**Closed by christian-fei** 2020-07-16 15:02 UTC

**Comment by HorlogeSkynet** [comment] 2020-07-16 16:24
Thanks @christian-fei, thanks @ecupaio :heart:

(If I may though, I think specifying the project version in the final build asset made sense and could be useful in many ways)
